sudo: false
cache:
  directories:
    - $HOME/.cache/pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7.13"

env:
  - VERSION="6.1"

install:
  - pip install python-magic
  - git  --depth=1 clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install --update pyth
  - travis_install_nightly ${VERSION}
  - $HOME/maintainer-quality-tools/travis/travis_install_nightly ${VERSION}

script:
  - travis_run_flake8
  - travis_run_tests ${VERSION}

after_success:
  coveralls
